# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-03 19:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ubigeo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
            ],
            options={
                'proxy': True,
                'verbose_name_plural': 'Departamentos',
                'verbose_name': 'Departamento',
            },
            bases=('ubigeo.ubigeo',),
        ),
        migrations.CreateModel(
            name='District',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('ubigeo.ubigeo',),
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('ubigeo.ubigeo',),
        ),
    ]
